"""Property tests for the placement reader over its whole input space.

The reader is a parser, and the example tests beside it pin the shapes this
repository happens to declare today. Three of the defects found in review were
inputs nobody had thought to write down: a composite expression whose
references went unread, a quoted string treated as falsy, and a padded
expression read as the bare one. Generating the space is how that class is
covered rather than enumerated.

Each property states an invariant the contracts depend on, so a reader change
that quietly narrowed one would fail here rather than in a workflow months
later.
"""

from __future__ import annotations

import typing as typ
from unittest import mock

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from tests.helpers import ci_placement as reader

if typ.TYPE_CHECKING:
    import collections.abc as cabc
    import contextlib

    from tests.helpers.workflow_types import Job

#: Hypothesis's default deadline measures the host, not the code, and these
#: cases are trivial; a flaky contract test is worse than a slow one.
SETTINGS = settings(deadline=None, max_examples=200)

#: Horizontal whitespace that may sit *inside* an expression body without
#: changing it. Deliberately no newline: a line break in the parsed value is
#: the folded-scalar defect, refused by its own rule and generated by its own
#: property below. Padding *outside* the braces is a third thing, also refused.
INNER_SPACE = st.sampled_from(["", " ", "  ", "\t"])
#: The three junctions inside a fork body, drawn together so the property takes
#: one argument rather than three.
INNER_SPACING = st.tuples(INNER_SPACE, INNER_SPACE, INNER_SPACE)
LABELS = st.sampled_from([
    "ubuntu-latest",
    "ubuntu-22.04",
    "windows-2022",
    "macos-latest",
    "macos-15-intel",
    "ubicloud-standard-2",
    "ubicloud-standard-4",
])
PROPERTY_PATHS = st.sampled_from([
    reader.FORK_FIELD,
    "github.event.pull_request.head.repo.private",
    "matrix.os",
    "matrix.python-version",
    "needs.changes.outputs.bench",
])
MATRIX_KEYS = st.sampled_from(["os", "runner", "platform", "image-label"])


def declaring(
    declared: cabc.Mapping[str, object],
) -> contextlib.AbstractContextManager[object]:
    """Make the reader see one synthetic declaration, for one block.

    A context manager rather than `monkeypatch`: a function-scoped fixture is
    not reset between the inputs `@given` generates, so state would leak from
    one example to the next. Hypothesis fails the health check for exactly that
    reason, and suppressing it would keep the leak rather than remove it.

    Returns
    -------
    contextlib.AbstractContextManager[object]
        A context manager that installs the declaration and restores the real
        reader on exit, including when the block raises.
    """

    def _declared(workflow_name: str, job_name: str) -> Job:
        """Return the synthetic declaration whatever job is asked for."""
        del workflow_name, job_name
        return typ.cast("Job", declared)

    return mock.patch.object(reader, "job", _declared)


@SETTINGS
@given(
    condition=PROPERTY_PATHS,
    fork_arm=LABELS,
    owned_arm=LABELS,
    spacing=INNER_SPACING,
)
def test_a_fork_expression_preserves_its_arms_by_position(
    condition: str,
    fork_arm: str,
    owned_arm: str,
    spacing: tuple[str, str, str],
) -> None:
    """Read the arms by position however the body is spaced.

    Position is the whole point: an expression naming one hosted and one paid
    label in either order satisfies a membership test, and one of those two
    orders sends every fork to a runner it cannot obtain.
    """
    before, after_condition, after_or = spacing
    body = (
        f"{before}{condition}{after_condition}&& '{fork_arm}' ||{after_or}'{owned_arm}'"
    )
    with declaring({"runs-on": f"${{{{{body}}}}}", "steps": []}):
        placed = reader.placement("w.yml", "j")
    assert placed.kind == "fork", f"body {body!r} read as {placed.kind}"
    assert placed.fork == fork_arm, f"fork arm was {placed.fork!r}"
    assert placed.owned == owned_arm, f"owned arm was {placed.owned!r}"
    assert placed.references == frozenset({condition}), (
        f"condition read as {sorted(placed.references)}"
    )


@SETTINGS
@given(key=MATRIX_KEYS, labels=st.lists(LABELS, min_size=1, max_size=5, unique=True))
def test_a_matrix_placement_resolves_every_leg(key: str, labels: list[str]) -> None:
    """Resolve `runs-on` through the matrix rather than stopping at the key."""
    declared = {
        "runs-on": f"${{{{ matrix.{key} }}}}",
        "steps": [],
        "strategy": {"matrix": {"include": [{key: label} for label in labels]}},
    }
    with declaring(declared):
        placed = reader.placement("w.yml", "j")
    assert placed.kind == "matrix", f"read as {placed.kind}"
    assert placed.labels == frozenset(labels), (
        f"legs {labels} resolved to {sorted(placed.labels)}"
    )
    assert placed.references == frozenset({f"matrix.{key}"}), (
        f"references were {sorted(placed.references)}"
    )
    assert placed.owned is None, "a matrix placement has no single owned label"


@SETTINGS
@given(label=LABELS)
def test_a_literal_label_round_trips(label: str) -> None:
    """Report a bare label as itself, reading no expression from it.

    `ubuntu-22.04` is the case that matters: it carries a dot, and a reference
    reader that did not exclude literals would report it as a context property.
    """
    with declaring({"runs-on": label, "steps": []}):
        placed = reader.placement("w.yml", "j")
    assert placed.kind == "literal", f"{label!r} read as {placed.kind}"
    assert placed.labels == frozenset({label}), f"labels were {sorted(placed.labels)}"
    assert placed.references == frozenset(), (
        f"a literal reads no property, got {sorted(placed.references)}"
    )


@SETTINGS
@given(
    prefix=st.sampled_from(["", " ", "runner-", "ubuntu-"]),
    suffix=st.sampled_from(["", " ", "-latest"]),
    path=PROPERTY_PATHS,
)
def test_anything_around_an_expression_is_refused(
    prefix: str, suffix: str, path: str
) -> None:
    """Refuse a value that interpolates without being wholly an expression.

    GitHub substitutes into the surrounding string and keeps what is around it,
    so every one of these resolves to a label no runner matches. The empty
    prefix and suffix pair is excluded because that is the supported shape.
    """
    if not prefix and not suffix:
        return
    declared = {"runs-on": f"{prefix}${{{{ {path} }}}}{suffix}", "steps": []}
    with (
        declaring(declared),
        pytest.raises(AssertionError, match="interpolates its runner label"),
    ):
        reader.placement("w.yml", "j")


@SETTINGS
@given(
    condition=PROPERTY_PATHS,
    fork_arm=LABELS,
    owned_arm=LABELS,
    position=st.integers(min_value=0, max_value=3),
)
def test_a_line_break_anywhere_in_the_value_is_refused(
    condition: str, fork_arm: str, owned_arm: str, position: int
) -> None:
    """Refuse an embedded line break wherever the fold put it.

    A folded-scalar continuation indented one level deeper keeps its line break
    and puts a newline inside the expression. GitHub evaluates the broken value
    regardless, so a green run is not evidence and only the parsed document
    shows it. The break is generated at each junction rather than at the one
    place a handwritten fixture would put it.
    """
    parts = [condition, "&&", f"'{fork_arm}'", "||", f"'{owned_arm}'"]
    separators = [" "] * 4
    separators[position] = "\n"
    body = "".join(
        part + (separators[index] if index < len(separators) else "")
        for index, part in enumerate(parts)
    )
    with (
        declaring({"runs-on": f"${{{{{body}}}}}", "steps": []}),
        pytest.raises(AssertionError, match="embedded line break"),
    ):
        reader.placement("w.yml", "j")


@SETTINGS
@given(paths=st.lists(PROPERTY_PATHS, min_size=1, max_size=4, unique=True))
def test_every_property_in_a_composite_expression_is_read(
    paths: list[str],
) -> None:
    """Read every property a composite expression names, not the body.

    A body-level reader stops at the first `}`, which is inside `{0}`, and
    reports no reference at all. The job-name stability rule compares
    references, so that silence let an unstable name pass.
    """
    arguments = ", ".join(paths)
    template = "-".join(f"{{{index}}}" for index in range(len(paths)))
    value = f"a ${{{{ format('{template}', {arguments}) }}}} b"
    assert reader.references(value) == frozenset(paths), (
        f"{value!r} read {sorted(reader.references(value))}"
    )


#: Guards built the way a workflow builds them. Generated rather than listed,
#: because the risk here is a false positive on an ordinary condition, and a
#: rule that refused those would be switched off.
GUARD_SUBJECTS = st.sampled_from([
    "github.event_name",
    "github.ref",
    "needs.changes.outputs.bench",
    "matrix.python-suite",
    "inputs.publish-baseline",
])
GUARD_VALUES = st.sampled_from([
    "'push'",
    "'pull_request'",
    "'refs/heads/main'",
    "'true'",
    "'false'",
    "true",
])


#: A comparison and the two ways a workflow dresses it: negated, wrapped in
#: `${{ }}`, both, or neither. Drawn as one value so the property keeps a
#: readable signature.
GUARD_SHAPES = st.tuples(
    GUARD_SUBJECTS,
    st.sampled_from(["==", "!="]),
    GUARD_VALUES,
    st.booleans(),
    st.booleans(),
)


@SETTINGS
@given(shape=GUARD_SHAPES)
def test_a_real_guard_is_never_reported_as_dead(
    shape: tuple[str, str, str, bool, bool],
) -> None:
    """Keep the dead-lane rule off conditions that can be true.

    Note `'false'` among the generated values: GitHub treats a non-empty string
    as truthy, so a comparison against it is an ordinary guard on a job that
    runs. Encoding the quoted form as falsy was the defect this covers.
    """
    subject, operator, value, negated, wrapped = shape
    text = f"{subject} {operator} {value}"
    if negated:
        text = f"!({text})"
    if wrapped:
        text = f"${{{{ {text} }}}}"
    with declaring({"runs-on": "ubuntu-latest", "steps": [], "if": text}):
        assert not reader.never_runs("w.yml", "j"), (
            f"{text!r} names no falsy literal, so the job can run"
        )
