name: Build Pure Python Wheel
description: Builds a pure Python wheel using UV and uploads it as an artifact.
inputs:
  python-version:
    description: Python version to set up
    required: true
  out-dir:
    description: Directory to place built wheel
    required: false
    default: dist
  artifact-name:
    description: Name of the uploaded artifact
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
    - name: Build wheel
      shell: bash
      run: uv build --wheel --out-dir ${{ inputs.out-dir }}
    - name: Upload wheel artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.out-dir }}/*.whl
