"""Property coverage for aggregate stream-operation telemetry."""

from __future__ import annotations

import asyncio
import io
import typing as typ

from hypothesis import given, settings
from hypothesis import strategies as st

from cuprum._streams import _drain, _StreamConfig
from cuprum._streams_pump import _pump_stream
from cuprum.stream_events import StreamOperation, StreamOperationOutcome
from cuprum.stream_observation import observe_stream_operation


class _Reader:
    """Reader double that yields its queued chunks and then EOF."""

    def __init__(self, chunks: tuple[bytes, ...]) -> None:
        """Store the chunks that the reader will yield."""
        self._chunks = list(chunks)

    async def read(self, _: int) -> bytes:
        """Return the next chunk or the terminal EOF read."""
        return self._chunks.pop(0) if self._chunks else b""


class _Writer:
    """Writer double that records every accepted chunk."""

    def __init__(self) -> None:
        """Start with no accepted bytes."""
        self.data = bytearray()

    def write(self, chunk: bytes) -> None:
        """Record one accepted chunk."""
        self.data.extend(chunk)

    async def drain(self) -> None:
        """Accept completion of writer backpressure."""

    def write_eof(self) -> None:
        """Accept writer EOF."""

    def close(self) -> None:
        """Accept writer closure."""

    async def wait_closed(self) -> None:
        """Accept completion of writer closure."""


def _drain_config() -> _StreamConfig:
    """Build a capture-only configuration for generated drain cases."""
    return _StreamConfig(
        capture_output=True,
        echo_output=False,
        sink=io.StringIO(),
        encoding="utf-8",
        errors="replace",
    )


_CHUNKS = st.lists(st.binary(min_size=1, max_size=32), max_size=8).map(tuple)
_SETTINGS = settings(max_examples=30, deadline=None, derandomize=True)


@_SETTINGS
@given(chunks=_CHUNKS)
def test_aggregate_events_count_every_generated_read(chunks: tuple[bytes, ...]) -> None:
    """Drain and relay events aggregate generated chunks and their EOF read."""
    drain_events = []
    pump_events = []
    writer = _Writer()

    with observe_stream_operation(drain_events.append):
        asyncio.run(
            _drain(
                typ.cast("asyncio.StreamReader", _Reader(chunks)),
                _drain_config(),
            )
        )
    with observe_stream_operation(pump_events.append):
        asyncio.run(
            _pump_stream(
                typ.cast("asyncio.StreamReader", _Reader(chunks)),
                typ.cast("asyncio.StreamWriter", writer),
            )
        )

    expected_bytes = sum(map(len, chunks))
    expected_reads = len(chunks) + 1
    for event, operation in (
        (drain_events[0], StreamOperation.DRAIN),
        (pump_events[0], StreamOperation.PIPELINE_TRANSFER),
    ):
        assert event.operation is operation, "the event must retain its operation kind"
        assert event.outcome is StreamOperationOutcome.EOF, (
            "a generated finite reader must complete at EOF"
        )
        assert event.bytes_consumed == expected_bytes, (
            "the event must aggregate every returned payload byte"
        )
        assert event.read_operations == expected_reads, (
            "the event must count every chunk and the terminal EOF read"
        )
        assert event.duration_s >= 0.0, (
            "the event must report a non-negative monotonic duration"
        )
    assert writer.data == b"".join(chunks), "the relay must preserve generated bytes"
