"""Bounded, control-safe keepalive lines for quiet children.

The presentation half of the idle heartbeat: how one keepalive line is
rendered, where it is written, and how a failure to write it is reported. The
timing state machine that decides *when* a line is due lives in
``cuprum._idle_heartbeat``; nothing here reads a clock, a process, or a child's
output.

The line is generated by the parent for the parent. It goes to the parent's
stderr sink, is bounded so a keepalive can never come to dominate the log it
exists to keep legible, and is ASCII-safe so a destination with a narrower
encoding cannot turn a diagnostic into a failure.
"""

from __future__ import annotations

import dataclasses as dc
import inspect
import logging
import sys
import typing as typ

if typ.TYPE_CHECKING:
    import collections.abc as cabc


_LOGGER = logging.getLogger("cuprum.idle")

# One generated line, its newline included. Bounded so a keepalive can never
# come to dominate the log it exists to keep legible.
_MAX_IDLE_LINE_BYTES = 512
# Programme metadata is parent-supplied, but bounding it keeps the byte ceiling
# above the only defence against a pathological name.
_MAX_IDLE_SUBJECT_CHARS = 64
_PIPELINE_IDLE_SUBJECT = "pipeline output idle"


@dc.dataclass(frozen=True, slots=True)
class _LiveSink:
    """Resolve the parent's diagnostic sink at emission time."""

    configured: typ.IO[str] | None = None

    def __call__(self) -> typ.IO[str]:
        """Return the configured sink, or the live ``sys.stderr``."""
        if self.configured is not None:
            return self.configured
        return sys.stderr


def _never_open() -> bool:
    """Report that no mirrored line is unfinished."""
    return False


@dc.dataclass(frozen=True, slots=True)
class _IdleDiagnostic:
    """Render and write one bounded keepalive line per notification."""

    subject: str
    destination: cabc.Callable[[], typ.IO[str]]
    is_line_open: cabc.Callable[[], bool] = _never_open

    def write(self, *, elapsed_total: float, elapsed_idle: float) -> None:
        """Flush one keepalive line to the parent's diagnostic sink."""
        line = _render_idle_line(
            self.subject,
            elapsed_total=elapsed_total,
            elapsed_idle=elapsed_idle,
        )
        if self.is_line_open():
            # Presentation only: start on a fresh line rather than becoming the
            # tail of an unfinished mirrored one. Capture is untouched.
            line = f"\n{line}"
        sink = self.destination()
        sink.write(line)
        sink.flush()


def _idle_subject(program: str) -> str:
    """Render the built-in keepalive subject for one programme name."""
    return f"still running {_sanitize_subject(program)}"


def _sanitize_subject(program: str) -> str:
    """Render programme metadata as bounded, control-safe ASCII."""
    cleaned = "".join(
        char if char.isascii() and char.isprintable() else "?" for char in program
    )
    return cleaned[:_MAX_IDLE_SUBJECT_CHARS] or "program"


def _render_idle_line(
    subject: str,
    *,
    elapsed_total: float,
    elapsed_idle: float,
) -> str:
    """Render one bounded, control-safe, newline-terminated keepalive line."""
    body = (
        f"[cuprum] {subject} "
        f"(idle {_format_duration(elapsed_idle)}, "
        f"total {_format_duration(elapsed_total)})"
    )
    # ASCII-safe by construction: the line is written to a parent sink whose
    # encoding is not ours to choose, and a diagnostic that raised
    # ``UnicodeEncodeError`` would be a worse failure than a transliterated
    # name. Only the clamping below can shorten the result.
    encoded = f"{body}\n".encode("ascii", "replace")
    if len(encoded) > _MAX_IDLE_LINE_BYTES:
        encoded = encoded[: _MAX_IDLE_LINE_BYTES - 1] + b"\n"
    return encoded.decode("ascii")


def _format_duration(seconds: float) -> str:
    """Render a non-negative duration as a compact, bounded ASCII string."""
    total = max(0, int(seconds))
    hours, rest = divmod(total, 3600)
    minutes, secs = divmod(rest, 60)
    if hours:
        return f"{hours}h{minutes:02d}m"
    if minutes:
        return f"{minutes}m{secs:02d}s"
    return f"{secs}s"


def _report_notification_failure(error_type: str) -> None:
    """Report one sanitized idle-notification failure."""
    _LOGGER.warning(
        "idle_notification_disabled error=%s",
        error_type,
        extra={
            "cuprum_action": "idle_notification_disabled",
            "cuprum_error_type": error_type,
        },
    )


def _report_callback_result(result: object) -> None:
    """Report a non-``None`` ``on_idle`` return, closing any coroutine.

    Idle callbacks are synchronous by contract. An unawaited coroutine would
    otherwise surface later as an unrelated ``coroutine was never awaited``
    warning, so it is closed here and reported against the callback that
    produced it, mirroring the echo-observer precedent.
    """
    _LOGGER.warning(
        "idle_callback_returned_value result_type=%s",
        type(result).__name__,
        extra={
            "cuprum_action": "idle_callback_returned_value",
            "cuprum_result_type": type(result).__name__,
        },
    )
    if inspect.iscoroutine(result):
        result.close()


__all__ = [
    "_MAX_IDLE_LINE_BYTES",
    "_PIPELINE_IDLE_SUBJECT",
    "_IdleDiagnostic",
    "_LiveSink",
    "_format_duration",
    "_idle_subject",
    "_render_idle_line",
    "_report_callback_result",
    "_report_notification_failure",
]
